Repository CherryNetwork/substrate, pull requests merged in 2022-12, with the labels that each got.

#17 Cherry v0.9.32
  Cargo.lock
  client/cli/src/params/database_params.rs
  client/transaction-pool/src/enactment_state.rs
  client/transaction-pool/src/lib.rs
  frame/contracts/src/benchmarking/mod.rs
  frame/contracts/src/lib.rs
  frame/contracts/src/wasm/mod.rs
  frame/contracts/src/wasm/runtime.rs
  frame/transaction-payment/rpc/Cargo.toml
  frame/transaction-payment/rpc/runtime-api/Cargo.toml
  frame/transaction-payment/rpc/runtime-api/src/lib.rs
  frame/transaction-payment/rpc/src/lib.rs
  frame/transaction-payment/src/types.rs
  primitives/weights/src/lib.rs
Labels: upstream-merge, A0-pleasereview, B0-silent, C7-high ❗️, D1-audited 👍

#19 fix: collective proposals origin
  frame/collective/src/lib.rs
Labels: bug, A0-pleasereview, B0-silent, C7-high ❗️, D1-audited 👍

#21 fix: treasury's initial supply for Mainnet regenesis
  frame/treasury/src/lib.rs
Labels: enhancement, Governance, A0-pleasereview, B0-silent, C7-high ❗️, D1-audited 👍

#22 fix: Saturated conversion import
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, B0-silent, C7-high ❗️, D1-audited 👍
